APPLY_FIXES: none # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE
  - SPELL

DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - MARKDOWN_MARKDOWN_LINK_CHECK

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false

REPOSITORY_TRIVY_ARGUMENTS:
  - "--severity=HIGH,CRITICAL"
  - "--ignore-unfixed"

REPOSITORY_KICS_CONFIG_FILE: .kics.yaml
REPOSITORY_KICS_ARGUMENTS:
  - --fail-on=HIGH
